name: Game Documentation
on:
  push:
    branches:
    - master

permissions:
  pages: write
  deployments: write
  id-token: write
  
env:
  CONAN_REVISIONS_ENABLED: 1

jobs:
  docs:
    runs-on: windows-latest

    environment:
     name: github-pages
     url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check Installed Software
        run: where git & where python & where pip
        shell: cmd
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: pip install conan
        
      - name: Install Doxygen
        run: conan download doxygen/1.9.4@#19fe2ac34109f3119190869a4d0ffbcb --remote conancenter
        
      - name: Run Doxygen
        run: doxygen Doxygen\Doxyfile
        
      - name: Upload Docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: Documentation\html
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Deploy To GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
